# ----------------------------------------------------------------------------
#
# Package             : mongo-python-driver
# Source Repo         : https://github.com/mongodb/mongo-python-driver
# Travis Job Link     : https://travis-ci.com/github/asellappen/mongo-python-driver/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python
arch:
  #  - amd64
    - ppc64le
python:
  #- 3.4
  #- 3.5
  #- 3.6
  #- 3.7
  - 3.8
  #- pypy3.5
sudo: required
services:
  - mongodb
before_install:
  - sudo apt-get update
  - sudo apt-get install -y mongodb
  - sudo service mongod start
  
script: PYMONGO_MUST_CONNECT=1 python setup.py test
